// messages_generated.dart
//
// Pre-generated from messages.fbs.  Regenerate after schema changes with:
//   flatc --dart -o example/lib/ example/linux/libmessage/messages.fbs
//
// ignore_for_file: unused_import, unused_field, camel_case_types

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;

// ── Payload union type constants ──────────────────────────────────────────────
// Mirror of the C++ Payload enum generated by flatc.
abstract final class Payload {
  static const int none     = 0;
  static const int colorMsg = 1;
  static const int textMsg  = 2;
}

// ── ColorMsg ──────────────────────────────────────────────────────────────────
// table ColorMsg { r: uint8; g: uint8; b: uint8; }
//
// vtable offsets: r=4  g=6  b=8

class ColorMsg {
  const ColorMsg._(this._bc, this._o);
  final fb.BufferContext _bc;
  final int _o;

  int get r => const fb.Uint8Reader().vTableGet(_bc, _o, 4, 0);
  int get g => const fb.Uint8Reader().vTableGet(_bc, _o, 6, 0);
  int get b => const fb.Uint8Reader().vTableGet(_bc, _o, 8, 0);
}

class _ColorMsgReader extends fb.TableReader<ColorMsg> {
  const _ColorMsgReader();
  @override
  ColorMsg createObject(fb.BufferContext bc, int offset) =>
      ColorMsg._(bc, offset);
}

// ── TextMsg ───────────────────────────────────────────────────────────────────
// table TextMsg { text: string (required); }
//
// vtable offsets: text=4

class TextMsg {
  const TextMsg._(this._bc, this._o);
  final fb.BufferContext _bc;
  final int _o;

  // vTableGetNullable: StringReader<String> — returns null when field absent.
  String? get text => const fb.StringReader().vTableGetNullable(_bc, _o, 4);
}

class _TextMsgReader extends fb.TableReader<TextMsg> {
  const _TextMsgReader();
  @override
  TextMsg createObject(fb.BufferContext bc, int offset) =>
      TextMsg._(bc, offset);
}

// ── Message ───────────────────────────────────────────────────────────────────
// table Message { id: uint32; payload: Payload; }
//
// A union field expands into two consecutive vtable slots:
//   payloadType (uint8 discriminant) → offset 6
//   payload     (table reference)    → offset 8
//
// vtable offsets: id=4  payloadType=6  payload=8

class Message {
  const Message._(this._bc, this._o);

  /// Deserialise a [Message] from a FlatBuffers byte buffer.
  ///
  /// [bytes] is the zero-copy view from the service wrapper:
  ///   final bytes = svc.getMessageBytes(msg);
  static Message? fromBuffer(Uint8List bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return const _MessageReader().read(rootRef, 0);
  }

  final fb.BufferContext _bc;
  final int _o;

  /// Monotonically increasing sequence number set by the C++ worker.
  int get id => const fb.Uint32Reader().vTableGet(_bc, _o, 4, 0);

  /// Union discriminant — compare with [Payload] constants.
  int get payloadType => const fb.Uint8Reader().vTableGet(_bc, _o, 6, 0);

  /// The actual payload; cast after checking [payloadType].
  ///
  /// ```dart
  /// switch (msg.payloadType) {
  ///   case Payload.colorMsg: final c = msg.payload as ColorMsg; …
  ///   case Payload.textMsg:  final t = msg.payload as TextMsg;  …
  /// }
  /// ```
  // vTableGetNullable: TableReader returns null when the field is absent.
  Object? get payload {
    switch (payloadType) {
      case Payload.colorMsg:
        return const _ColorMsgReader().vTableGetNullable(_bc, _o, 8);
      case Payload.textMsg:
        return const _TextMsgReader().vTableGetNullable(_bc, _o, 8);
      default:
        return null;
    }
  }
}

class _MessageReader extends fb.TableReader<Message> {
  const _MessageReader();
  @override
  Message createObject(fb.BufferContext bc, int offset) =>
      Message._(bc, offset);
}
