// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable

library fcb_msgs;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;

class PayloadTypeId {
  final int value;
  const PayloadTypeId._(this.value);

  factory PayloadTypeId.fromValue(int value) {
    final result = values[value];
    if (result == null) {
      throw StateError('Invalid value $value for bit flag enum PayloadTypeId');
    }
    return result;
  }

  static PayloadTypeId? _createOrNull(int? value) =>
      value == null ? null : PayloadTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 2;
  static bool containsValue(int value) => values.containsKey(value);

  static const PayloadTypeId NONE = PayloadTypeId._(0);
  static const PayloadTypeId ColorMsg = PayloadTypeId._(1);
  static const PayloadTypeId TextMsg = PayloadTypeId._(2);
  static const Map<int, PayloadTypeId> values = {
    0: NONE,
    1: ColorMsg,
    2: TextMsg,
  };

  static const fb.Reader<PayloadTypeId> reader = _PayloadTypeIdReader();

  @override
  String toString() {
    return 'PayloadTypeId{value: $value}';
  }
}

class _PayloadTypeIdReader extends fb.Reader<PayloadTypeId> {
  const _PayloadTypeIdReader();

  @override
  int get size => 1;

  @override
  PayloadTypeId read(fb.BufferContext bc, int offset) =>
      PayloadTypeId.fromValue(const fb.Uint8Reader().read(bc, offset));
}

///  RGB colour value emitted by the worker.
class ColorMsg {
  ColorMsg._(this._bc, this._bcOffset);
  factory ColorMsg(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ColorMsg> reader = _ColorMsgReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get r => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get g => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 6, 0);
  int get b => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 8, 0);

  @override
  String toString() {
    return 'ColorMsg{r: ${r}, g: ${g}, b: ${b}}';
  }
}

class _ColorMsgReader extends fb.TableReader<ColorMsg> {
  const _ColorMsgReader();

  @override
  ColorMsg createObject(fb.BufferContext bc, int offset) =>
      ColorMsg._(bc, offset);
}

class ColorMsgBuilder {
  ColorMsgBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addR(int? r) {
    fbBuilder.addUint8(0, r);
    return fbBuilder.offset;
  }

  int addG(int? g) {
    fbBuilder.addUint8(1, g);
    return fbBuilder.offset;
  }

  int addB(int? b) {
    fbBuilder.addUint8(2, b);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ColorMsgObjectBuilder extends fb.ObjectBuilder {
  final int? _r;
  final int? _g;
  final int? _b;

  ColorMsgObjectBuilder({int? r, int? g, int? b}) : _r = r, _g = g, _b = b;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(3);
    fbBuilder.addUint8(0, _r);
    fbBuilder.addUint8(1, _g);
    fbBuilder.addUint8(2, _b);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

///  Arbitrary UTF-8 text.
class TextMsg {
  TextMsg._(this._bc, this._bcOffset);
  factory TextMsg(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<TextMsg> reader = _TextMsgReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get text =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'TextMsg{text: ${text}}';
  }
}

class _TextMsgReader extends fb.TableReader<TextMsg> {
  const _TextMsgReader();

  @override
  TextMsg createObject(fb.BufferContext bc, int offset) =>
      TextMsg._(bc, offset);
}

class TextMsgBuilder {
  TextMsgBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addTextOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class TextMsgObjectBuilder extends fb.ObjectBuilder {
  final String? _text;

  TextMsgObjectBuilder({String? text}) : _text = text;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? textOffset = _text == null
        ? null
        : fbBuilder.writeString(_text!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, textOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class Message {
  Message._(this._bc, this._bcOffset);
  factory Message(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Message> reader = _MessageReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  PayloadTypeId? get payloadType => PayloadTypeId._createOrNull(
    const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 6),
  );
  dynamic get payload {
    switch (payloadType?.value) {
      case 1:
        return ColorMsg.reader.vTableGetNullable(_bc, _bcOffset, 8);
      case 2:
        return TextMsg.reader.vTableGetNullable(_bc, _bcOffset, 8);
      default:
        return null;
    }
  }

  @override
  String toString() {
    return 'Message{id: ${id}, payloadType: ${payloadType}, payload: ${payload}}';
  }
}

class _MessageReader extends fb.TableReader<Message> {
  const _MessageReader();

  @override
  Message createObject(fb.BufferContext bc, int offset) =>
      Message._(bc, offset);
}

class MessageBuilder {
  MessageBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addId(int? id) {
    fbBuilder.addUint32(0, id);
    return fbBuilder.offset;
  }

  int addPayloadType(PayloadTypeId? payloadType) {
    fbBuilder.addUint8(1, payloadType?.value);
    return fbBuilder.offset;
  }

  int addPayloadOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class MessageObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final PayloadTypeId? _payloadType;
  final dynamic _payload;

  MessageObjectBuilder({int? id, PayloadTypeId? payloadType, dynamic payload})
    : _id = id,
      _payloadType = payloadType,
      _payload = payload;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? payloadOffset = _payload?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(3);
    fbBuilder.addUint32(0, _id);
    fbBuilder.addUint8(1, _payloadType?.value);
    fbBuilder.addOffset(2, payloadOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
